version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: koyjak
    ports:
      - "5432:5432"  # Use 5432 on both host and container
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/koyjak?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  pgdata: